# Chapter 12 : Parallelizing Neural Network Training with Pytorch

## PyTorch and training performance

### Performance challenges 

Python is limited by the Global Interpreter Lock (GIL) to one core.  Since MLP network with many hidden layers can quickly grow in parameters, this limitation can be bypassed by using the GPU, which are better value for computations.

### What is PyTorch?

*PyTorch* is a programming interface for running machine learning algorithms.  It allows a script to use CPU and GPU and TLU devices. 

PyTorch is built around a computation graph composed of a set of nodes.  Each node represents an operation with zero or more inputs or outputs. 

PyTorch uses tensors which are analogous to NumPy arrays, but optimized for GPU computations.  They act as scalars (rank 1), vectors (rank 2), matrices (rank 3), etc. 

### How to learn PyTorch

- understand tensors and how to use an manipulate them
- understand how to load data and use `torch.utils.data`
- use `torch.nn` neural network module, and then build machine learning modules

## First Steps with PyTorch
- install via `pip`

### Making Tensors

Tensors can be made from lists and NumPy arrays.
- Pass lists to `.tensor`
- Pass arrays to `from_numpy`

In [1]:
import torch
import numpy as np
np.set_printoptions(precision=3)
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32) 
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


Just like an array, tensors have `.shape`:

In [2]:
t_ones = torch.ones(2, 3) 
print(t_ones)
t_ones.shape

tensor([[1., 1., 1.],
        [1., 1., 1.]])


torch.Size([2, 3])

A tensor of random values can be created:

In [19]:
rand_tensor = torch.rand(2,3)
print(rand_tensor)

tensor([[0.5098, 0.5946, 0.4730],
        [0.5654, 0.4023, 0.3465]])


### Manipulating the data type and shape of a tensor

`.to()` is used to cast to a different datatype:

In [20]:
t_a_new = t_a.to(torch.int64)
print(t_a_new.dtype)

torch.int64


Some operations need tensors of a certain rank; therefore, the size and/or shape of a tensor might need to be manipulated.

Transposing: use `.transpose`

In [21]:
t = torch.rand(3, 5)
t_tr = torch.transpose(t, 0, 1)
print(t.shape, ' --> ', t_tr.shape)

torch.Size([3, 5])  -->  torch.Size([5, 3])


Reshaping: use `.reshape`

In [23]:
t = torch.zeros(30)
t_reshape = t.reshape(5, 6) 
print(t.shape, ' ---> ', t_reshape.shape)

torch.Size([30])  --->  torch.Size([5, 6])


Removing a dimension: use `.squeeze`

In [24]:
t = torch.zeros(1, 2, 1, 4, 1)
t_sqz = torch.squeeze(t, 2)
print(t.shape, ' --> ', t_sqz.shape)

torch.Size([1, 2, 1, 4, 1])  -->  torch.Size([1, 2, 4, 1])
